import {
  ROUTER_SCRIPT_TEMPLATE_ANY,
  type LinkTechnology,
  type Operadora4g,
  type OwnerType,
  type RouterModel,
  type RouterRole,
  type RouterScriptCustomTemplateRow,
  type SwitchTopology,
} from "@/lib/routerScriptCustomTemplate";
import type { RouterScriptVariant } from "@/lib/routerScript";

const baseTemplateContentMap = import.meta.glob("../assets/router-script-templates/base/*.txt", {
  query: "?raw",
  import: "default",
  eager: true,
}) as Record<string, string>;

const getBaseTemplateContent = (fileName: string) => {
  const key = `../assets/router-script-templates/base/${fileName}`;
  const content = baseTemplateContentMap[key];
  if (!content) {
    throw new Error(`Template base '${fileName}' nao encontrado nos assets do projeto.`);
  }
  return content;
};

interface BaseTemplateDefinition {
  id: string;
  name: string;
  fileName: string;
  routerRole: RouterRole;
  model: RouterModel | typeof ROUTER_SCRIPT_TEMPLATE_ANY;
  technology: LinkTechnology | typeof ROUTER_SCRIPT_TEMPLATE_ANY;
  owner: OwnerType | typeof ROUTER_SCRIPT_TEMPLATE_ANY;
  operadora4g: Operadora4g | typeof ROUTER_SCRIPT_TEMPLATE_ANY;
  switchTopology: SwitchTopology | typeof ROUTER_SCRIPT_TEMPLATE_ANY;
  scriptVariant: RouterScriptVariant;
  notes: string;
}

const createBaseTemplate = (definition: BaseTemplateDefinition): RouterScriptCustomTemplateRow => ({
  id: definition.id,
  name: definition.name,
  router_role: definition.routerRole,
  model: definition.model,
  technology: definition.technology,
  owner: definition.owner,
  operadora_4g: definition.operadora4g,
  switch_topology: definition.switchTopology,
  script_variant: definition.scriptVariant,
  content: getBaseTemplateContent(definition.fileName),
  notes: definition.notes,
  is_active: true,
  created_at: null,
  updated_at: null,
  updated_by: null,
  source: "base",
});

export const BUNDLED_ROUTER_SCRIPT_TEMPLATES: RouterScriptCustomTemplateRow[] = [
  createBaseTemplate({
    id: "base-hpmsr900-4g-c-sw-tim",
    name: "HP900 4G C-SW (TIM)",
    fileName: "hpmsr900-4g-c-sw-tim.txt",
    routerRole: "backup",
    model: "hpmsr900",
    technology: "4g",
    owner: ROUTER_SCRIPT_TEMPLATE_ANY,
    operadora4g: "tim",
    switchTopology: "com-switch",
    scriptVariant: "completo",
    notes: "Base embarcada a partir do anexo HP900 4G C-SW (TIM).txt.",
  }),
  createBaseTemplate({
    id: "base-hpmsr900-4g-oi-s-sw",
    name: "HP900 4G Owner OI S-SW",
    fileName: "hpmsr900-4g-oi-s-sw.txt",
    routerRole: "backup",
    model: "hpmsr900",
    technology: "4g",
    owner: "oi",
    operadora4g: ROUTER_SCRIPT_TEMPLATE_ANY,
    switchTopology: "sem-switch",
    scriptVariant: "completo",
    notes: "Base embarcada a partir do anexo HP900 4G Owner Oi - S-SW.txt.",
  }),
  createBaseTemplate({
    id: "base-hpmsr900-4g-sencinet-s-sw-arqia",
    name: "HP900 4G Owner SCT S-SW (ARQIA)",
    fileName: "hpmsr900-4g-sencinet-s-sw-arqia.txt",
    routerRole: "backup",
    model: "hpmsr900",
    technology: "4g",
    owner: "sencinet",
    operadora4g: "arqia",
    switchTopology: "sem-switch",
    scriptVariant: "completo",
    notes: "Base embarcada a partir do anexo HP900 4G Owner SCT - S-SW (ARQIA).txt.",
  }),
  createBaseTemplate({
    id: "base-hpmsr900-4g-sencinet-s-sw-tim",
    name: "HP900 4G Owner SCT S-SW (TIM)",
    fileName: "hpmsr900-4g-sencinet-s-sw-tim.txt",
    routerRole: "backup",
    model: "hpmsr900",
    technology: "4g",
    owner: "sencinet",
    operadora4g: "tim",
    switchTopology: "sem-switch",
    scriptVariant: "completo",
    notes: "Base embarcada a partir do anexo HP900 4G Owner SCT - S-SW (TIM).txt.",
  }),
  createBaseTemplate({
    id: "base-hpmsr920-pri-s-sw",
    name: "HP920 PRI S-SW",
    fileName: "hpmsr920-pri-s-sw.txt",
    routerRole: "principal",
    model: "hpmsr920",
    technology: ROUTER_SCRIPT_TEMPLATE_ANY,
    owner: ROUTER_SCRIPT_TEMPLATE_ANY,
    operadora4g: ROUTER_SCRIPT_TEMPLATE_ANY,
    switchTopology: "sem-switch",
    scriptVariant: "completo",
    notes: "Base embarcada a partir do anexo HP920 PRI S-SW.txt.",
  }),
  createBaseTemplate({
    id: "base-hpmsr931-oi-s-sw",
    name: "HP931 Owner OI S-SW",
    fileName: "hpmsr931-oi-s-sw.txt",
    routerRole: "principal",
    model: "hpmsr931",
    technology: ROUTER_SCRIPT_TEMPLATE_ANY,
    owner: "oi",
    operadora4g: ROUTER_SCRIPT_TEMPLATE_ANY,
    switchTopology: "sem-switch",
    scriptVariant: "completo",
    notes: "Base embarcada a partir do anexo HP931 Owner Oi S-SW.txt.",
  }),
  createBaseTemplate({
    id: "base-hp1002-4-4g-s-sw-arqia-bkp",
    name: "HP1002 ELSYS S-SW (ARQIA) BKP",
    fileName: "hp1002-4-4g-s-sw-arqia-bkp.txt",
    routerRole: "backup",
    model: "hp1002-4",
    technology: "4g",
    owner: ROUTER_SCRIPT_TEMPLATE_ANY,
    operadora4g: "arqia",
    switchTopology: "sem-switch",
    scriptVariant: "completo",
    notes: "Base embarcada a partir do anexo HP1002 ELSYS S-SW (ARQIA) BKP.txt.",
  }),
  createBaseTemplate({
    id: "base-hp1002-4-oi-s-sw",
    name: "HP1002 Owner OI S-SW",
    fileName: "hp1002-4-oi-s-sw.txt",
    routerRole: "principal",
    model: "hp1002-4",
    technology: ROUTER_SCRIPT_TEMPLATE_ANY,
    owner: "oi",
    operadora4g: ROUTER_SCRIPT_TEMPLATE_ANY,
    switchTopology: "sem-switch",
    scriptVariant: "completo",
    notes: "Base embarcada a partir do anexo HP1002 Owner Oi S-SW.txt.",
  }),
  createBaseTemplate({
    id: "base-huawei-4g",
    name: "HUAWEI 4G",
    fileName: "huawei-4g-base.txt",
    routerRole: "backup",
    model: "huawei",
    technology: "4g",
    owner: ROUTER_SCRIPT_TEMPLATE_ANY,
    operadora4g: ROUTER_SCRIPT_TEMPLATE_ANY,
    switchTopology: ROUTER_SCRIPT_TEMPLATE_ANY,
    scriptVariant: "completo",
    notes: "Base embarcada a partir do anexo HUAWEI 4G.txt.",
  }),
  createBaseTemplate({
    id: "base-huawei-ar121-4g-oi-c-sw-tim",
    name: "Huawei AR121 4G OWNER OI C-SW TIM",
    fileName: "huawei-ar121-4g-oi-c-sw-tim.txt",
    routerRole: "backup",
    model: "huawei",
    technology: "4g",
    owner: "oi",
    operadora4g: "tim",
    switchTopology: "com-switch",
    scriptVariant: "completo",
    notes: "Base embarcada a partir do anexo Huawei AR121 4G OWNER OI C-SW TIM.txt.",
  }),
  createBaseTemplate({
    id: "base-huawei-pri-c-sw",
    name: "Huawei PRI C-SW",
    fileName: "huawei-pri-c-sw.txt",
    routerRole: "principal",
    model: "huawei",
    technology: ROUTER_SCRIPT_TEMPLATE_ANY,
    owner: ROUTER_SCRIPT_TEMPLATE_ANY,
    operadora4g: ROUTER_SCRIPT_TEMPLATE_ANY,
    switchTopology: "com-switch",
    scriptVariant: "completo",
    notes: "Base embarcada a partir do anexo Huawei PRI C-SW.txt.",
  }),
  createBaseTemplate({
    id: "base-huawei-pri-s-sw",
    name: "Huawei PRI S-SW",
    fileName: "huawei-pri-s-sw.txt",
    routerRole: "principal",
    model: "huawei",
    technology: ROUTER_SCRIPT_TEMPLATE_ANY,
    owner: ROUTER_SCRIPT_TEMPLATE_ANY,
    operadora4g: ROUTER_SCRIPT_TEMPLATE_ANY,
    switchTopology: "sem-switch",
    scriptVariant: "completo",
    notes: "Base embarcada a partir do anexo Huawei PRI S-SW.txt.",
  }),
  createBaseTemplate({
    id: "base-hpmsr900-4g-oi-c-sw-vivo",
    name: "MSR 900 4G OWNER OI C-SW VIVO",
    fileName: "hpmsr900-4g-oi-c-sw-vivo.txt",
    routerRole: "backup",
    model: "hpmsr900",
    technology: "4g",
    owner: "oi",
    operadora4g: "vivo",
    switchTopology: "com-switch",
    scriptVariant: "completo",
    notes: "Base embarcada a partir do anexo MSR 900 4G OWNER OI C-SW VIVO.txt.",
  }),
  createBaseTemplate({
    id: "base-nqa-pri-hp",
    name: "NQA PRI HP",
    fileName: "nqa-pri-hp.txt",
    routerRole: "principal",
    model: ROUTER_SCRIPT_TEMPLATE_ANY,
    technology: ROUTER_SCRIPT_TEMPLATE_ANY,
    owner: ROUTER_SCRIPT_TEMPLATE_ANY,
    operadora4g: ROUTER_SCRIPT_TEMPLATE_ANY,
    switchTopology: ROUTER_SCRIPT_TEMPLATE_ANY,
    scriptVariant: "nqa",
    notes: "Base embarcada a partir do anexo NQA PRI HP.txt.",
  }),
  createBaseTemplate({
    id: "base-nqa-pri-huawei",
    name: "NQA PRI HUAWEI",
    fileName: "nqa-pri-huawei.txt",
    routerRole: "principal",
    model: "huawei",
    technology: ROUTER_SCRIPT_TEMPLATE_ANY,
    owner: ROUTER_SCRIPT_TEMPLATE_ANY,
    operadora4g: ROUTER_SCRIPT_TEMPLATE_ANY,
    switchTopology: ROUTER_SCRIPT_TEMPLATE_ANY,
    scriptVariant: "nqa",
    notes: "Base embarcada a partir do anexo NQA PRI HUAWEI.txt.",
  }),
  createBaseTemplate({
    id: "base-hpmsr900-vsat-s-sw",
    name: "VSAT S-SW 900 script",
    fileName: "hpmsr900-vsat-s-sw-base.txt",
    routerRole: "backup",
    model: "hpmsr900",
    technology: "vsat",
    owner: ROUTER_SCRIPT_TEMPLATE_ANY,
    operadora4g: ROUTER_SCRIPT_TEMPLATE_ANY,
    switchTopology: "sem-switch",
    scriptVariant: "completo",
    notes: "Base embarcada a partir do anexo VSAT S-SW 900 script.txt.",
  }),
  createBaseTemplate({
    id: "base-hpmsr900-4g-generic",
    name: "900 script",
    fileName: "hpmsr900-4g-base.txt",
    routerRole: "backup",
    model: "hpmsr900",
    technology: "4g",
    owner: ROUTER_SCRIPT_TEMPLATE_ANY,
    operadora4g: ROUTER_SCRIPT_TEMPLATE_ANY,
    switchTopology: ROUTER_SCRIPT_TEMPLATE_ANY,
    scriptVariant: "completo",
    notes: "Base embarcada a partir do anexo 900 script.txt.",
  }),
  createBaseTemplate({
    id: "base-hpmsr920-4g-generic",
    name: "920 script",
    fileName: "hpmsr920-4g-base.txt",
    routerRole: "backup",
    model: "hpmsr920",
    technology: "4g",
    owner: ROUTER_SCRIPT_TEMPLATE_ANY,
    operadora4g: ROUTER_SCRIPT_TEMPLATE_ANY,
    switchTopology: ROUTER_SCRIPT_TEMPLATE_ANY,
    scriptVariant: "completo",
    notes: "Base embarcada a partir do anexo 920 script.txt.",
  }),
  createBaseTemplate({
    id: "base-bgp-oi-hp-secondary",
    name: "BGP OWNER OI CONFIGURACAO NO ROTEADOR HP SECUNDARIO",
    fileName: "bgp-oi-hp-secondary.txt",
    routerRole: "backup",
    model: ROUTER_SCRIPT_TEMPLATE_ANY,
    technology: ROUTER_SCRIPT_TEMPLATE_ANY,
    owner: "oi",
    operadora4g: ROUTER_SCRIPT_TEMPLATE_ANY,
    switchTopology: ROUTER_SCRIPT_TEMPLATE_ANY,
    scriptVariant: "bgp",
    notes: "Base embarcada a partir do anexo BGP OWNER OI CONFIGURACAO NO ROTEADOR HP SECUNDARIO.txt.",
  }),
  createBaseTemplate({
    id: "base-bgp-oi-hp-pri-family",
    name: "BGP OWNER OI CONFIGURACAO NO ROTEADOR HP931-20-11-900",
    fileName: "bgp-oi-hp-pri-family.txt",
    routerRole: "principal",
    model: ROUTER_SCRIPT_TEMPLATE_ANY,
    technology: ROUTER_SCRIPT_TEMPLATE_ANY,
    owner: "oi",
    operadora4g: ROUTER_SCRIPT_TEMPLATE_ANY,
    switchTopology: ROUTER_SCRIPT_TEMPLATE_ANY,
    scriptVariant: "bgp",
    notes: "Base embarcada a partir do anexo BGP OWNER OI CONFIGURACAO NO ROTEADOR HP931-20-11-900.txt.",
  }),
  createBaseTemplate({
    id: "base-bgp-oi-hp1002-primary",
    name: "BGP OWNER OI CONFIGURACAO NO ROTEADOR HP1002 PRIMARIO",
    fileName: "bgp-oi-hp1002-primary.txt",
    routerRole: "principal",
    model: "hp1002-4",
    technology: ROUTER_SCRIPT_TEMPLATE_ANY,
    owner: "oi",
    operadora4g: ROUTER_SCRIPT_TEMPLATE_ANY,
    switchTopology: ROUTER_SCRIPT_TEMPLATE_ANY,
    scriptVariant: "bgp",
    notes: "Base embarcada a partir do anexo BGP OWNER OI CONFIGURACAO NO ROTEADOR HP1002 PRIMARIO.txt.",
  }),
  createBaseTemplate({
    id: "base-bgp-oi-huawei-secondary",
    name: "BGP OWNER OI CONFIGURACAO NO ROTEADOR HUAWEI SECUNDARIO",
    fileName: "bgp-oi-huawei-secondary.txt",
    routerRole: "backup",
    model: "huawei",
    technology: ROUTER_SCRIPT_TEMPLATE_ANY,
    owner: "oi",
    operadora4g: ROUTER_SCRIPT_TEMPLATE_ANY,
    switchTopology: ROUTER_SCRIPT_TEMPLATE_ANY,
    scriptVariant: "bgp",
    notes: "Base embarcada a partir do anexo BGP OWNER OI CONFIGURACAO NO ROTEADOR HUAWEI SECUNDARIO.txt.",
  }),
  createBaseTemplate({
    id: "base-bgp-sencinet-hp931",
    name: "BGP OWNER SCT ROTEADOR HP931",
    fileName: "bgp-sencinet-hp931.txt",
    routerRole: "principal",
    model: "hpmsr931",
    technology: ROUTER_SCRIPT_TEMPLATE_ANY,
    owner: "sencinet",
    operadora4g: ROUTER_SCRIPT_TEMPLATE_ANY,
    switchTopology: ROUTER_SCRIPT_TEMPLATE_ANY,
    scriptVariant: "bgp",
    notes: "Base embarcada a partir do anexo BGP OWNER SCT ROTEADOR HP931.txt.",
  }),
  createBaseTemplate({
    id: "base-bgp-sencinet-hp1002",
    name: "BGP OWNER SCT ROTEADOR HP1002",
    fileName: "bgp-sencinet-hp1002.txt",
    routerRole: "principal",
    model: "hp1002-4",
    technology: ROUTER_SCRIPT_TEMPLATE_ANY,
    owner: "sencinet",
    operadora4g: ROUTER_SCRIPT_TEMPLATE_ANY,
    switchTopology: ROUTER_SCRIPT_TEMPLATE_ANY,
    scriptVariant: "bgp",
    notes: "Base embarcada a partir do anexo BGP OWNER SCT ROTEADOR HP1002.txt.",
  }),
  createBaseTemplate({
    id: "base-bgp-sencinet-hp-secondary",
    name: "BGP OWNER SCT ROUTER SECUNDARIO - HP",
    fileName: "bgp-sencinet-hp-secondary.txt",
    routerRole: "backup",
    model: ROUTER_SCRIPT_TEMPLATE_ANY,
    technology: ROUTER_SCRIPT_TEMPLATE_ANY,
    owner: "sencinet",
    operadora4g: ROUTER_SCRIPT_TEMPLATE_ANY,
    switchTopology: ROUTER_SCRIPT_TEMPLATE_ANY,
    scriptVariant: "bgp",
    notes: "Base embarcada a partir do anexo BGP OWNER SCT ROUTER SECUNDARIO - HP.txt.",
  }),
  createBaseTemplate({
    id: "base-bgp-sencinet-huawei-secondary",
    name: "BGP OWNER SCT ROUTER SECUNDARIO - HUAWEI",
    fileName: "bgp-sencinet-huawei-secondary.txt",
    routerRole: "backup",
    model: "huawei",
    technology: ROUTER_SCRIPT_TEMPLATE_ANY,
    owner: "sencinet",
    operadora4g: ROUTER_SCRIPT_TEMPLATE_ANY,
    switchTopology: ROUTER_SCRIPT_TEMPLATE_ANY,
    scriptVariant: "bgp",
    notes: "Base embarcada a partir do anexo BGP OWNER SCT ROUTER SECUNDARIO - HUAWEI.txt.",
  }),
  createBaseTemplate({
    id: "base-cisco-principal",
    name: "CISCO",
    fileName: "cisco-principal-base.txt",
    routerRole: "principal",
    model: "cisco1900",
    technology: ROUTER_SCRIPT_TEMPLATE_ANY,
    owner: ROUTER_SCRIPT_TEMPLATE_ANY,
    operadora4g: ROUTER_SCRIPT_TEMPLATE_ANY,
    switchTopology: ROUTER_SCRIPT_TEMPLATE_ANY,
    scriptVariant: "completo",
    notes: "Base embarcada a partir do anexo CISCO.txt.",
  }),
  createBaseTemplate({
    id: "base-hp1002-4-oi-c-sw",
    name: "HP 1002 OWNER OI C-SW",
    fileName: "hp1002-4-oi-c-sw.txt",
    routerRole: "principal",
    model: "hp1002-4",
    technology: ROUTER_SCRIPT_TEMPLATE_ANY,
    owner: "oi",
    operadora4g: ROUTER_SCRIPT_TEMPLATE_ANY,
    switchTopology: "com-switch",
    scriptVariant: "completo",
    notes: "Base embarcada a partir do anexo HP 1002 OWNER OI C-SW.txt.",
  }),
  createBaseTemplate({
    id: "base-hpmsr931-oi-c-sw",
    name: "HP MSR931 OWNER OI C-SW",
    fileName: "hpmsr931-oi-c-sw.txt",
    routerRole: "principal",
    model: "hpmsr931",
    technology: ROUTER_SCRIPT_TEMPLATE_ANY,
    owner: "oi",
    operadora4g: ROUTER_SCRIPT_TEMPLATE_ANY,
    switchTopology: "com-switch",
    scriptVariant: "completo",
    notes: "Base embarcada a partir do anexo HP MSR931 OWNER OI C-SW.txt.",
  }),
];
