// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const hasSupabaseConfig = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

if (!hasSupabaseConfig) {
  console.error(
    "Configuracao ausente do Supabase. Defina VITE_SUPABASE_URL e VITE_SUPABASE_PUBLISHABLE_KEY no ambiente.",
  );
}

const safeSupabaseUrl = SUPABASE_URL || "https://invalid.supabase.co";
const safeSupabaseKey = SUPABASE_PUBLISHABLE_KEY || "invalid-key";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(safeSupabaseUrl, safeSupabaseKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

export const supabaseConfigError = hasSupabaseConfig
  ? null
  : "Configuracao de ambiente ausente: VITE_SUPABASE_URL e/ou VITE_SUPABASE_PUBLISHABLE_KEY.";
